"""initial_requests_table

Revision ID: c8485a0ed721
Revises: 
Create Date: 2026-02-22 02:51:06.783251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8485a0ed721'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('requested_model', sa.String(), nullable=True),
    sa.Column('routed_model', sa.String(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_id'), 'requests', ['id'], unique=False)
    op.create_index(op.f('ix_requests_status'), 'requests', ['status'], unique=False)
    op.create_index(op.f('ix_requests_task_type'), 'requests', ['task_type'], unique=False)
    op.create_index(op.f('ix_requests_tenant_id'), 'requests', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_requests_timestamp'), 'requests', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requests_timestamp'), table_name='requests')
    op.drop_index(op.f('ix_requests_tenant_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_task_type'), table_name='requests')
    op.drop_index(op.f('ix_requests_status'), table_name='requests')
    op.drop_index(op.f('ix_requests_id'), table_name='requests')
    op.drop_table('requests')
    # ### end Alembic commands ###
